apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dso-demo
  name: dso-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dso-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dso-demo
    spec:
      serviceAccountName: dso-demo
      automountServiceAccountToken: false
      containers:
      - image: custlynotts/dsodemo
        name: dsodemo
        ports:
        - containerPort: 8080
        securityContext:
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 11000
        resources: 
          requests:
             cpu: "50m"
             memory: "128Mi"
          limits:
             cpu: "250m"
             memory: "256Mi"
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
status: {}
